const PICK_DE = [
    'Ene mene muh, Dran bist Du!',
    'Angsthase, Pfeffernase, Morgen kommt der Osterhase, Zieht dir deine Hose aus, Übermorgen Nikolaus, Zieht sie wieder an, Und Du bist dran!',
    'Auf einem Gummi-Gummi-Berg. Da wohnt ein Gummi-Gummi-Zwerg. Der Gummi-Gummi-Zwerg. Hat eine Gummi-Gummi-Frau. Die Gummi-Gummi-Frau. Hat ein Gummi-Gummi-Kind. Das Gummi-Gummi-Kind. Hat ein Gummi-Gummi-Kleid. Das Gummi-Gummi-Kleid. Hat ein Gummi-Gmmi-Loch. Und Du bist es doch!',
    'Eine kleine Haselmaus, zog sich mal die Hosen aus, zog sie wieder an, und Du bist dran.',
    'Hexenhaus und schwarzer Kater, Fledermäuse als Berater, Hexenmus und Zauberkuss, Du bist der, der suchen muss!',
    'Hinde Hande Hundekuchen, Einer von uns wird gleich fluchen, Piste, Paste, Pustekuchen, Wir sind frei und Du musst suchen!',
    'Ich und du, Müllers Kuh, Müllers Esel das bist Du!',
    'Kasper hat so laut gelacht, Dass im Haus der Balken kracht, Das Haus fällt ein, Und Du musst es sein!',
    'Ritze ratze ritze ratze, Was macht heut die Miezekatze? Die Mieze bäckt uns Kuchen, Und Du musst suchen!',
    'Eine kleine Micky Maus, Zieht sich ihre Hose aus, zieht sie wieder an, und Du bist dran!',
	'Auf der Stiege steht ein Hahn, kräht ganz laut: Du bist dran!',
	'Eins zwei drei vier Finkenstein, wer nicht will, der muss es sein.',
	'Rinke, ranke Rosen, alles ohne Hosen, Hosen an und Du bist dran.',
	'Eins zwei drei vier fünf sechs sieben, in der Schule wird geschrieben, in der Schule wird gelacht, bis der Lehrer Pitsch-Patsch macht.',
	'Wer hat den schönsten Schuh? Den schönsten Schuh, den hast nur Du.',
	'Auf dem Berge Simoni, wohnt der Schneider Kikriki. Seine Frau die Margarete, saß auf dem Balkon und nähte. Fiel herab, fiel herab, und das linke Bein brach ab. Kommt der Doktor angerannt, mit der Nadel in der Hand, näht es an, näht es an, dass sie wieder laufen kann.',
	'Antchen Dantchen Dittchen Dattchen, Tebber Di Bebber Di Dittchen Dattchen, Tebber Di Bebber Di Buh, und dran bist Du!'
];

const COUNT_OUT_DE = [
    'Ene mene muh. Raus bist du!', 
    'Eins zwei drei vier fünf sechs sieben, eine alte Frau kocht Rüben, eine alte Frau kocht Speck, und Du bist weg!',
    'Eins zwei drei, Butter mit Brei, Salz mit Speck, Und Du bist weg.',
    'Eins zwei drei vier fünf sechs sieben acht neun. Das Schiff fährt übern Rhein. Das Schiff, das ist zerbrochen. Geh raus, Du alter Knochen.',
    'Eins zwei drei vier fünf, Der Storch hat keine Strümpf, Der Frosch hat kein Haus, Und Du musst raus.',
    'Ein Elefant aus Sachsenhausen, Ließ nen Furz ins Telefon sausen, Ließ ihn wieder raus, Und Du bist drauß.',
	'Eins zwei drei vier auf dem Klavier, sitzt eine Maus und Du bist draus.',
    'Eins zwei, Papagei, Drei vier, Offizier, Fünf sechs, alte Hex, Sieben acht, Kaffee gemacht, Neun zehn, weiter gehn, Elf zwölf, junge Wölf, Dreizehn Vierzehn, Haselnuss, Fünfzehn Sechszehn, Du bist druß!',
    'Ene mene ming-mang, ching-chang, sing-sang, Ene mene pipifax, eia weia weg.',
	'Rinke, ranke Rosen, alles ohne Hosen, Hosen an, Hosen aus, und Du bist raus.',
	'Eine kleine Mücke saß auf der Brücke - eine zweite kam hinzu und raus bist Du.',
	'Oberhoppel hoppelhase hoppelt in dem Stoppelgrase, hoppelt in das Hasenhaus und Du bist raus.',
	'Eins Zwei Drei Vier Fünf Sechs Sieben, guten Appetit ihr Lieben.',
	'Ene mene Mopel, wer frisst Popel, süß und saftig, eine Mark und Achtzig, eine Mark und zehn und Du kannst gehn. ',
	'Zickel zackel zockel, der Ochse ist kein Gockel. Der Gockel keine Maus und Du bist drauß.',
	'Hasenspeck und Hasendreck, Eins zwei drei, und Du bist weg.',
	'Ene dene Tintenfass, geh zur Schul und lerne was. Wenn du was gelernet hast, komm nach Haus und sag mir was! Eins zwei drei, und Du bist frei!',
	'Eine kleine Dickmadam, fuhr mit der Eisenbahn. Eisenbahn die krachte, Dickmadam die lachte. I, a, u draus bist Du!',
	'Guten Tag, auf Wiedersehen, tut mir leid, Du musst jetzt gehn.',
	'Eine kleine Spitzmaus lief ums Rathaus, wollte sich was kaufen, hatte sich verlaufen, kam die Mutter mit dem Stock, haut sie auf den Unterrock. Unterrock war lose, haut sie auf die Hose. Hose war kaputt, und Du bist furt.',
	'Hinter grünen Hecken wollen wir uns verstecken. Unter dichten Büschen sollt ihr uns erwischen. Such dich jeder ein Versteck, eins zwei drei, und Du bist weg.',
    'Ene mene miste, Es rappelt in der Kiste, Ene mene meck, Und Du bist weg.',
    'Es war einmal ein Mann, Der hatte einen Schwamm, Der Schwamm war ihm zu nass, Da ging er auf die Gass, Die Gass war ihm zu kalt, Da ging er in den Wald, Der Wald war ihm zu grün, Da ging er nach Berlin, Berlin war ihm zu klein, Da ging er wieder heim, Daheim wars ihm zu nett, Da stieg er in das Bett, Im Bett war eine Maus, Da sprang er wieder raus, Und du bist drauß!',
    'Hasenspeck und Hasendreck, Eins zwei drei und Du bist weg!',
	'Eichen, Buchen, Tannen, und du mußt fangen. Eichen, Tannen, Buchen, und Du musst suchen.',
	'Auf dem Berge Sinai wohnt der Schneider Kikriki. Schaut mit seiner Brille raus: Eins zwei drei, und Du bist raus!',
	'Ritz und Ratz, Maus und Katz, Katz und Maus, Du bist drauß! Eins zwei drei, und Du bist frei!',
    'Hopp, hopp Has, Hüpf in das Gras, Hüpf wieder raus, Und Du bist drauß!',
    'Mein Finger geht im Kreise, Auf eine kurze Reise, Und bleibt mein Finger stehen, Dann darfst du endlich gehen!',
    'Feuersalamander, Beine auseinander, Beine wieder zu, und raus bist Du!',
    'Rennfahrer Bibele, Hat em Ärschle a Zwiebele, furzts wieder raus, und du bisch raus.',
    'Enne denne dubbe denne, dubbe denne dalia, ebbe bebbe bembio, bio bio buff, und Du bisch duss.'
];

module.exports = { rhymes: [PICK_DE, COUNT_OUT_DE] };